### ISSUE TITLE
On some pages, `.ShowMoreCard.AddonDescription` is missing bottom left&right border radius

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#6886]
### Describe the problem and steps to reproduce it:
1. Visit https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/ and https://addons.mozilla.org/en-US/firefox/addon/beanfun-extension-check/
2. Compare the bottom border radius of their `About this extension` cards.

### What happened?
Unlike beanfun's listing page, Violentmonkeys' `.ShowMoreCard.AddonDescription` card is missing `.Card--no-footer` so it doesn't get
    
    .Card--no-footer .Card-contents {
        border-bottom-left-radius: 9px;
        border-bottom-right-radius: 9px;
    }

### Anything else we should know?
![screenshot_2018-11-10 violentmonkey get this extension for firefox en-us](https://user-images.githubusercontent.com/8336638/48303687-287a5a00-e533-11e8-90ea-7dbcea4a8e56.png)

**Comment by HosseinMarzban** [comment]
We can remove this tow lines:
```css
.Card-header{
...
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
...
}
```

And then add this two lines to the parent like below:
```css
.Addon .Card{
....
    border-radius: 9px;
    overflow: hidden;
....
}
```
Is that proper way? @willdurand

**Comment by willdurand** [comment]
mmh, I don't think it is that simple unfortunately. This is a known bug, because this card is sometimes "compacted" (with a "show more" button to expand its content) for small screens.

**Comment by HosseinMarzban** [comment]
@willdurand, you right, that one was hardcode, what about this one:
```css
@media (min-width: 720px){
    .Card-contents{
       ....
       border-radius: 0 0 9px 9px;
       ....
    }
}
```
this one definitely work, and does not effect when "compact" in small screens.
